# Generated by Django 5.2 on 2025-04-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('picture', models.ImageField(upload_to='dogs/')),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
