# Generated by Django 5.2 on 2025-04-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogFoodRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=100)),
                ('sunday_morning', models.CharField(max_length=255)),
                ('sunday_evening', models.CharField(max_length=255)),
                ('monday_morning', models.CharField(max_length=255)),
                ('monday_evening', models.CharField(max_length=255)),
                ('tuesday_morning', models.CharField(max_length=255)),
                ('tuesday_evening', models.CharField(max_length=255)),
                ('wednesday_morning', models.CharField(max_length=255)),
                ('wednesday_evening', models.CharField(max_length=255)),
                ('thursday_morning', models.CharField(max_length=255)),
                ('thursday_evening', models.CharField(max_length=255)),
                ('friday_morning', models.CharField(max_length=255)),
                ('friday_evening', models.CharField(max_length=255)),
                ('saturday_morning', models.CharField(max_length=255)),
                ('saturday_evening', models.CharField(max_length=255)),
            ],
        ),
    ]
