# Generated by Django 5.2 on 2025-04-05 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_dog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogfoodroutine',
            name='dog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.dog'),
        ),
    ]
