# Generated by Django 5.2 on 2025-04-06 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_dogfoodroutine_dog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogHealthRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=100)),
                ('date1', models.CharField(max_length=255)),
                ('health_check1', models.CharField(max_length=255)),
                ('vaccination1', models.CharField(max_length=255)),
                ('date2', models.CharField(max_length=255)),
                ('health_check2', models.CharField(max_length=255)),
                ('vaccination2', models.CharField(max_length=255)),
                ('date3', models.CharField(max_length=255)),
                ('health_check3', models.CharField(max_length=255)),
                ('vaccination3', models.CharField(max_length=255)),
                ('date4', models.CharField(max_length=255)),
                ('health_check4', models.CharField(max_length=255)),
                ('vaccination4', models.CharField(max_length=255)),
                ('date5', models.CharField(max_length=255)),
                ('health_check5', models.CharField(max_length=255)),
                ('vaccination5', models.CharField(max_length=255)),
                ('date6', models.CharField(max_length=255)),
                ('health_check6', models.CharField(max_length=255)),
                ('vaccination6', models.CharField(max_length=255)),
                ('dog', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.dog')),
            ],
        ),
    ]
