# Generated by Django 5.2 on 2025-04-06 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_doghealthroutine'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogGroomingRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=100)),
                ('date01', models.DateField(blank=True, null=True)),
                ('grooming01', models.CharField(blank=True, max_length=255, null=True)),
                ('date02', models.DateField(blank=True, null=True)),
                ('grooming02', models.CharField(blank=True, max_length=255, null=True)),
                ('date03', models.DateField(blank=True, null=True)),
                ('grooming03', models.CharField(blank=True, max_length=255, null=True)),
                ('date04', models.DateField(blank=True, null=True)),
                ('grooming04', models.CharField(blank=True, max_length=255, null=True)),
                ('dog', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.dog')),
            ],
        ),
    ]
