# Generated by Django 5.2 on 2025-04-06 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_catfoodroutine'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatHealthRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('date11', models.CharField(max_length=255)),
                ('health_check11', models.CharField(max_length=255)),
                ('vaccination11', models.CharField(max_length=255)),
                ('date22', models.CharField(max_length=255)),
                ('health_check22', models.CharField(max_length=255)),
                ('vaccination22', models.CharField(max_length=255)),
                ('date33', models.CharField(max_length=255)),
                ('health_check33', models.CharField(max_length=255)),
                ('vaccination33', models.CharField(max_length=255)),
                ('date44', models.CharField(max_length=255)),
                ('health_check44', models.CharField(max_length=255)),
                ('vaccination44', models.CharField(max_length=255)),
                ('date55', models.CharField(max_length=255)),
                ('health_check55', models.CharField(max_length=255)),
                ('vaccination55', models.CharField(max_length=255)),
                ('date66', models.CharField(max_length=255)),
                ('health_check66', models.CharField(max_length=255)),
                ('vaccination66', models.CharField(max_length=255)),
                ('cat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.cat')),
            ],
        ),
    ]
