# Generated by Django 5.2 on 2025-04-06 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_cathealthroutine'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatGroomingRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('date101', models.DateField(blank=True, null=True)),
                ('grooming101', models.CharField(blank=True, max_length=255, null=True)),
                ('date102', models.DateField(blank=True, null=True)),
                ('grooming102', models.CharField(blank=True, max_length=255, null=True)),
                ('date103', models.DateField(blank=True, null=True)),
                ('grooming103', models.CharField(blank=True, max_length=255, null=True)),
                ('date104', models.DateField(blank=True, null=True)),
                ('grooming104', models.CharField(blank=True, max_length=255, null=True)),
                ('cat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.dog')),
            ],
        ),
    ]
