# Generated by Django 5.2 on 2025-04-06 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_catgroomingroutine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catgroomingroutine',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.cat'),
        ),
    ]
