# Generated by Django 5.2 on 2025-05-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_cat_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroomingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('address', models.TextField()),
            ],
        ),
    ]
